### PR TITLE
update GNOME runtime to 3.30

### PR DESCRIPTION
**Pull request by eszlari**

### CODE REVIEW

**Comment by Hjdskes** [comment]
Has the version of librsvg been updated in the runtime? See

**Comment by Hjdskes** [comment]
Ugh stupid phone moving buttons around

**Comment by eszlari** [comment]
The runtime has 2.44.12 atm:
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/blob/18.08/elements/desktop/librsvg.bst

2.44.7 should fix 334:
https://gitlab.gnome.org/GNOME/librsvg/blob/librsvg-2.44/NEWS

**Comment by Hjdskes** [comment]
Cool, thanks. I'll take this for a test later this week when I can find some time!

**Comment by whot** [comment]
Works fine for me here, thanks1

**Comment by whot** [comment]
Huh, I didn't even notice that this wasn't the main piper repository. I've taken that patch and applied it to piper now as well, commit https://github.com/libratbag/piper/commit/f4aa6c69921d38ec9c2a07f6e0866437fb47d1de

**Pull request merged**
